import React from 'react';
import { getImage } from '../image'

export default () => {
  return <section className="article">
    <h1 className="article__title">About the beer</h1>
    <div>
      <img alt="clint" className="image--full" src={ getImage('/clint-photo.jpeg')} />
    </div>
    <div className="article__content">
      <p>Hi all. Welcome back to Watford Rugby Clubs 7th annual Real Ale and Cider Festival. So much has changed in the last year and I hope that these positive changes are reflected in the real ale and cider selection.</p>
      <p>So, what’s different? Well for starters, and very sadly, the Bree Louise and their owners, Karen and Craig Douglas are not directly involved with the festival anymore. I say ‘directly’ because they remain our inspiration and an integral foundation of this festival. When Martin Lee and myself first came up with this ridiculous idea, it was, it was Craig and Karen who ‘taught a man how to fish’ so to speak. Their passion and dedication to good and versatile product, along with a heart of gold, inspired my brother Desmond and I to open our own micro-pub in Hemel Hempstead. Monks Inn boasts 10 real ales, 5 gravity and 5 handles, plus 6 still cider handles and a great gin selection. When you Google us, or better still, <a href="https://www.facebook.com/pages/category/Pub/Monks-Inn-2064181233798241/">join and follow our Facebook page</a>, you will see that The Bree lives on albeit a smaller format. Indeed when you come in, you will feel like you are sitting at the same table as the Bree…which in fact you would be. The kindness of Craig and Karen is there to see.</p>
      <p>So it would be very wrong if Monks Inn didn’t accept the torch The Bree passed on and we are proud to partner with a club where the people champion the ethos of rugby so passionately. This ethos is shared by local organisations like Watford 2nd Cubs & Scouts who donate the use of their big green canvas marquee that announces to the world that it’s on!!!!</p>
      <p>Onto the beer and cider. In the short space of trading, Monks has been awarded Best Newcomer by CAMRA Mid Chiltern Branch. That’s because we have discovered some brilliant new Locales. You will find a few old faithful’s like Windsor & Eton, Rebellion, Tring and 3Brewers. But we have added some newbie’s we discovered like Paradigm, Chiltern and Popes Yard. Stuff I never ever heard of until Monks are in like Beerblefish, New River and Buntingford. From further afield we have Titanic (Stoke-on-Trent), Salopian (Shropshire) and Wantsum (East Kent). And the styles are different. Firstly you will notice a lot more dark beers. Titanic Plum Porter. If you haven’t gone there you haven’t lived. In fact a beer card says this is the first to go. We have Farr (St Albans) Black Listed. And Get this!!! Popes Yard!!!King Street Dusk!!! English Dark Lager!!!Cummoonn!!! Get the front door!!! Not to mention, my ‘One for the Road’ beer, Rudgate Ruby Mild. My ‘on my death bed’ last beer. Introduced to me by my beer mentor and father in law, Mick Catlin.</p>
      <p>Cider wise Ginger and Chilli making a comeback as is Bee Sting Perry, the latter being the foundation of the traditional ‘Beasting Friday’ which will show its impact on the players Saturday morning.</p>
      <p>Finally we have insulated jackets on this year after last year’s temperature impacted the profits. You see if we don’t move the beer we don’t make money. This club are tiny in comparison to neighbours. This fund raiser not only contributes to kids kit, but also shores up emergency bills and such. It sounds like I’m pulling heart strings and I am. This is a genuine club, with genuine people, and genuine problems. Don’t forget to take beer home with you. These sealed containers give you 4 days in the fridge. Tell your friends to come down. Especially on the Saturday. It’s a huge community affair and a great laugh.</p>
      <p>Finally and most importantly. To you our dedicated followers. We are happy to welcome the local Watford fans, Beer tickers, CAMRA Committee’s and members and especially the guest accompanying the rugby players. Must mention the dedicated ‘Monkonians’ who are attending this year. Thank you all from our hearts. You inspire us to continue.</p>
      <p>Love you long time</p>
    </div>
    <div className="article__signature">Clint Whitaker</div>
  </section>;
}